### ISSUE TITLE
Integration Test Tracking: Vault Module

### ISSUE THREAD

**Issue by vuong177** [onomyprotocol/reserve#26]
## Description
This issue tracks the progress and tasks related to the integration tests for the Vault module ## Tasks
### Vault Features

- [ ] Implement test for CreateVault
- [ ] Implement test for Deposit
- [ ] Implement test for Withdraw
- [ ] Implement test for Mint
- [ ] Implement test for Repay
- [ ] Implement tests for `GetVault` and `GetVault` functions
- [ ] Add/remove allowed deposit token
- [ ] Implement tests for VaultsManager, Vaults collections

### Liquidate Features
Implement tests for liquidation logic (details to be specified)

### BeginBlocker
- [ ] Implement test for UpdateVaultsDebt in BeginBlocker
